#!/usr/bin/env bash
# Build the Rust engine to WebAssembly and embed it for the web component.
#   ./scripts/build-wasm.sh            # opt-level from Cargo.toml (3)
#   OPT=s ./scripts/build-wasm.sh      # smaller binary
# Uses the wasm32 target when rustup has it; otherwise rebuilds core+alloc from a
# local rust-src (Ubuntu's rustc-1.91 + rust-1.91-src, as in the build sandbox).
set -euo pipefail
here="$(cd "$(dirname "$0")/.." && pwd)"
cd "$here/engine"
export CARGO_PROFILE_RELEASE_OPT_LEVEL="${OPT:-3}"
# Keep intermediate engine builds separate from the source tree.
export CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-$here/engine/.target}"
if command -v rustup >/dev/null && rustup target list --installed 2>/dev/null | grep -q '^wasm32-unknown-unknown$'; then
  cargo build --release --target wasm32-unknown-unknown
else
  CARGO_BIN="${CARGO_BIN:-cargo-1.91}"
  RUSTFLAGS="-C linker=wasm-ld -C linker-flavor=wasm-ld" RUSTC_BOOTSTRAP=1 \
    "$CARGO_BIN" build --release --target wasm32-unknown-unknown \
    -Zbuild-std=core,alloc -Zbuild-std-features=panic_immediate_abort
fi
wasm="$CARGO_TARGET_DIR/wasm32-unknown-unknown/release/lodeflow_layout.wasm"
cp "$wasm" "$here/web/src/lodeflow_layout.wasm"
node -e '
const fs = require("fs");
const b = fs.readFileSync(process.argv[1]);
const out = "// Generated by scripts/build-wasm.sh — the layout engine, base64-encoded.\n" +
  "// " + b.length + " bytes of WebAssembly.\nconst wasm: string =\n  \"" + b.toString("base64") + "\";\nexport default wasm;\n";
fs.writeFileSync(process.argv[2], out);
console.log("wasm", b.length, "bytes →", process.argv[2]);
' "$here/web/src/lodeflow_layout.wasm" "$here/web/src/wasm-inline.ts"
